### ISSUE TITLE
Error when running PPModelTest

### ISSUE THREAD

**Issue by MareikeJaniak** [dsilvestro/PyRate#27]
Hi!

I'm getting an error when running the PPModelTest command from the PyRate tutorial. The full command and the resulting error is below. It looks like it might be a small issue with a deprecated numpy command?

Best, 
Mareike

python ~/software/PyRate/PyRate.py ~/software/PyRate/example_files/Canis_example/Canis_pbdb_data_PyRate.py -qShift ~/software/PyRate/example_files/epochs_q.txt -PPmodeltest

                 PyRate - v3.0 - 20201021

          Bayesian estimation of origination,
           extinction and preservation rates
              from fossil occurrence data

                 pyrate.help@gmail.com

Module FastPyRateC was loaded.

 Canis_pbdb_data_PyRate ['/home/users/mjaniak/software/PyRate/example_files/Canis_example/Canis_pbdb_data_PyRate.py'] 

The analysis includes 18 species (0 were excluded)
[5.333, 2.58, 0.0117] 10.193827 0.0
Using Gamma priors on the birth-death rates (G_l[1.1,1.1], G_m[1.1,1.1]).

('Using', 5, 'species for model testing')
('HPP* max likelihood:', -352.1902730582955, 'q rate:', array([5.945]))
('TPP* max likelihood:', -271.04259368721006, 'q rates:', array([ 0.761,  4.542, 14.06 ,  0.914]))
('NHPP* max likelihood:', array([-563.947]), 'q rate:', array([5.447]), '\n')
/home/users/mjaniak/software/PyRate/pyrate_lib/PPmodeltest.py:244: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  Liks = np.array([resHPPm[0],liknhpp_Exp,resTPPm[0]])
/home/users/mjaniak/software/PyRate/pyrate_lib/PPmodeltest.py:158: RuntimeWarning: divide by zero encountered in true_divide
  return (2*df-2*lik + abs(2*df*(df+1)/(s-df-1.)))
('models:', array(['HPP', 'NHPP', 'TPP'], dtype='<U4'))
('AICc scores:', array([707.7138794499243, array([1131.227]), inf], dtype=object))
Traceback (most recent call last):
  File "/home/users/mjaniak/software/PyRate/PyRate.py", line 4817, in <module>
    PPmodeltest.run_model_testing(fossil,q_shift=times_q_shift,min_n_fossils=2,verbose=1)
  File "/home/users/mjaniak/software/PyRate/pyrate_lib/PPmodeltest.py", line 286, in run_model_testing
    """ % (best_model[0], other_models[0], round(deltaAICs_[0],3), sig[0], \
TypeError: type numpy.ndarray doesn't define __round__ method

**Comment by dsilvestro** [comment]
Hi @MareikeJaniak thank you for reporting the problem - I just pushed an update to the `pyrate_lib/PPmodeltest.py` file that should fix the issue.

**Comment by MareikeJaniak** [comment]
Thanks so much @dsilvestro! It works without issues now!
