### ISSUE TITLE
Module FastPyRateC is not found on mac M1

### ISSUE THREAD

**Issue by Yue1108** [dsilvestro/PyRate#32]
Dear expert,

  I got "Module FastPyRateC was not found" when I run analysis on Mac M1 Pro. I choose to install FastPyRateC library atuomatically, it failed and got error: 
>Could not find suitable distribution for Requirement.parse('FastPyRateC==1.0')
>_FastPyRateC.cpython-310-darwin.so
> done
>############################
>############################
>Cleaning up.
> done
>############################
 >An error must avec occured during the installation.
 > Try to install the library manually.

then I install it manually, at the step **Compilethe library** : it got error like:
>FastPyRateC.cpp:8:10: fatal error: 'boost/math/distributions.hpp' file not found
>#include <boost/math/distributions.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>1 error generated.
>error: command '/usr/bin/clang' failed with exit code 1

so how could I solve this problem? is this a M1 chip issue? because it works fine with my old computer with Inter core. 

Thanks for you help!

Best regarads,
Yue

**Comment by thauffe** [comment]
Hi Yue,

This should be fixed now but be sure to use a python version build for arm Macs instead of rosetta translated versions.

Best,
Torsten
