### ISSUE TITLE
Two potential fixes in PyRateContinuous.py

### ISSUE THREAD

**Issue by zhangchicool** [dsilvestro/PyRate#34]
1. line 401: 
    age = all_events_temp2[0,i]  -->  age = all_events[i]
2. line 424:
    t=np.loadtxt(summary_file, skiprows=np.max(1,int(args.b)))  -->
    t=np.loadtxt(summary_file, skiprows=np.max([1,int(args.b)]))

**Comment by thauffe** [comment]
Thank you Chi!
