### ISSUE TITLE
pyrate.py "'float' object cannot be interpreted as an integer"

### ISSUE THREAD

**Issue by LauravanHolstein** [dsilvestro/PyRate#38]
Hi there, 

When I try to run anything with PyRate.py (including trying to check the PyRate input file with the  _Canis_  example from the [tutorial](https://github.com/dsilvestro/PyRate/blob/master/tutorials/pyrate_tutorial_1.md#generate-pyrate-input-file-option-1)), I get the following error: 

`Module FastPyRateC was loaded.
Traceback (most recent call last):
  File "/Users/lauravanholstein/PyRate/PyRate/PyRate.py", line 4469, in <module>
    d3 = max(args.tR,1.01) # avoid win size < 1
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: 'float' object cannot be interpreted as an integer`

Seems to have something to do with how Python 3 does integer division. I'm running PyRate on a Mac (M1, 13.3.1) and have Python 3 installed. Any help would be appreciated! 
Best wishes, 
Laura

**Comment by thauffe** [comment]
Hi Laura,

This should be fixed with the latest PyRate update but please let us know if you face more issues.
One library on which PyRate depends changed it's behavior and we are currently figuring out where we need to make adjustments.

Best,
Torsten
