### ISSUE TITLE
Error message when trying to download FastPyrateC using curl

### ISSUE THREAD

**Issue by megaraptor1** [dsilvestro/PyRate#39]
I am attempting to download the FastPyrateC library for Windows 10. I have made sure to have SWIG and curl installed beforehand. After changing the directory to ModulePyrateC, when I attempt to download the boost C++ library using the following command...

> curl -fsSL (https://boostorg.jfrog.io/artifactory/main/release/1.66.0/source/boost_1_66_0.zip)

I get the following error message.

> curl: (3) URL using bad/illegal format or missing URL

I tried replacing the parenthesis with quotation marks, but that also does not seem to work.

**Comment by thauffe** [comment]
Hi,

We have updated the instructions for the latest version of boost.

However, we have not tried to download and compile FastPyRateC under Wiindows. Please report if it is working!

**Comment by thauffe** [comment]
Hi,

Please try the latest PyRate version. We compiled the fastPyRateC library for the latest versions of PyRate.

If you still want to compile it on your own, then this is the procedure that worked for us:

1. Install swig and add it to the Path of your system variables
2. Install [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) 
3. Install [Microsoft Visual Studio](https://visualstudio.microsoft.com/vs/) with the tool chains for python development and C++
4. Use the powershell and not the cmd command prompt and move to 
`cd ...\PyRate\pyrate_lib\fastPyRateC\ModulePyrateC`
6. Download boost 
`curl https://boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.gz -o boost_1_82_0.tar.gz`
7. Unpack boost
`tar -xf boost_1_82_0.tar.gz`
8. Move boost into the current folder
`mv boost_1_82_0/boost .
9. Create the C++/Python interface typing: 
`swig -c++ -python FastPyRateC.i`
10. Compile the library: 
`python setup.py build`
You should have two new files in the folder (FastPyRateC.py, FastPyRateC_wrap.cxx)`
11. Clean up
`rm boost_1_82_0.tar.gz`
`rm -r boost_1_82_0`
`rm -r boost`
12. Rename _\build\lib.win-amd64-3.X\_FastPyRateC.cp3X-win_amd64.pyd_ to __FastPyRateC.pyd_, where X represents your version of python
13. Move the pyd file into ...\PyRate\pyrate_lib\fastPyRateC\Windows\py3X

Best wishes,
Torsten

**Comment by megaraptor1** [comment]
I tried the instructions given and they failed at step 8: ```swig -c++ -python FastPyRateC.i```

I get the error message ```Unable to find file 'FastPyRateC.i'.```

Also, I had to change the previous step from ````mv boost_1_82_0/boost .``` to ```move boost_1_82_0/boost``` because the previous command only works on a UNIX machine.
