### ISSUE TITLE
"inconsistent use of tabs and spaces in indentation" in MCDD

### ISSUE THREAD

**Issue by LauravanHolstein** [dsilvestro/PyRate#40]
Hi there, 

I've tried running an MCDD analysis with [these data](https://github.com/dsilvestro/PyRate/files/12129627/hominin_occurrence_1_Grj_se_est_forDD.txt.zip) and I get the following error:
 `File "/Users/lauravanholstein/Python_coding/PyRate/PyRate/PyRateMCDD.py", line 270
    m0A=m0
TabError: inconsistent use of tabs and spaces in indentation`. 

I've tried to run the MCDD analysis with the canid example file, and get the same error. I'm running PyRate on a Mac M1. Any help would be appreciated! 

Cheers, 
Laura

**Comment by thauffe** [comment]
Hi Laura,

This should be fixed now. Please note that the fixed version is in the same directory as all other PyRate functions. 

You probably tried to run your analysis with:
`python PyRate_for_Python2/PyRateMCCD`

While now you should use:
`python PyRateMCCD`

Good luck!
