### ISSUE TITLE
Possible Discrepancy With `PyRate` Licensing

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [dsilvestro/PyRate#49]
Within the README, I see:

> PyRate is licensed under a [AGPLv3 License](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)#summary).

But within the Wiki, I see:

> This work is licensed under a [Creative Commons Attribution-NonCommercial 4.0 International License](http://creativecommons.org/licenses/by-nc/4.0/).

My assumption is that AGPLv3 is the correct license and the Wiki was not updated. This seems, practically speaking, to be a minor issue but still possibly has negative EV should some legal headache ever occur. Assuming most people will defer to README over Wiki though.

**Comment by dsilvestro** [comment]
thanks this is now fixed.
